//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AsyncGenerator.TestCases;

namespace AsyncGenerator.Tests.DocumentationComments.Input
{
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial class Remarks22
	{

		/// <remarks>
		/// Header
		/// <see cref="SimpleFile" />
		///
		/// Footer
		/// </remarks>
		public Task TestAsync()
		{
			return SimpleFile.ReadAsync();
		}

		/// <remarks>
		/// Header
		/// <see cref="SimpleFile" />
		///
		/// Footer
		/// </remarks>>
		public Task Test2Async()
		{
			return SimpleFile.ReadAsync();
		}

		/// <summary>
		/// My summary
		/// </summary>
		/// <remarks>
		/// Header
		/// <see cref="SimpleFile" />
		///
		/// Footer
		/// </remarks>
		public Task Test3Async()
		{
			return SimpleFile.ReadAsync();
		}

		/// <summary>
		/// My summary
		/// </summary>
		/// <param name="content"></param>
		/// <remarks>
		/// Header
		/// <see cref="SimpleFile" />
		///
		/// Footer
		/// </remarks>
		public Task Test4Async(string content)
		{
			return SimpleFile.WriteAsync(content);
		}

		/// <summary>
		/// My summary
		/// </summary>
		/// <param name="content"></param>
		/// <remarks>
		/// Header
		/// <see cref="SimpleFile" />
		///
		/// Footer
		/// </remarks>>
		public Task Test5Async(string content)
		{
			return SimpleFile.WriteAsync(content);
		}

	}
}
